FROM node:9.9.0
ARG VERSION_TAG
RUN git clone -b $VERSION_TAG https://github.com/DuoSoftware/DVP-ToDoListService.git /usr/local/src/todolistservice
RUN cd /usr/local/src/todolistservice;
WORKDIR /usr/local/src/todolistservice
RUN npm install

CMD [ "node", "/usr/local/src/todolistservice/app.js" ]